# Generated by Django 6.0.4 on 2026-06-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
