# Generated by Django 6.0.4 on 2026-06-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_drink_rename_menuitem_pizza"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("image_url", models.TextField()),
                ("allergens", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("PIZZA", "Pizza"), ("DRINK", "Drink")],
                        default="PIZZA",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Drink",
        ),
        migrations.DeleteModel(
            name="Pizza",
        ),
    ]
